spring:
  datasource:
    # ??? ???? h2 ??? ??
    # ?? ????? build.gradle ?? mysql ??? ?? ??
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    # mysql ????? ?? ?? ??
    # driver-class-name: com.mysql.cj.jdbc.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true  # H2 ??? ???
  jpa:
    hibernate:
      ddl-auto: update  # ?????? ??? ?? ??
    show-sql: true  # SQL ?? ??